/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-4168ca0e5efc137ea4ff4f0cf29358bf64e26f02
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkChangelogRequestBean : Request bean for bulk changelog retrieval
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkChangelogRequestBean {
    /// List of field IDs to filter changelogs
    #[serde(rename = "fieldIds", skip_serializing_if = "Option::is_none")]
    pub field_ids: Option<Vec<String>>,
    /// List of issue IDs/keys to fetch changelogs for
    #[serde(rename = "issueIdsOrKeys")]
    pub issue_ids_or_keys: Vec<String>,
    /// The maximum number of items to return per page
    #[serde(rename = "maxResults", skip_serializing_if = "Option::is_none")]
    pub max_results: Option<u32>,
    /// The cursor for pagination
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl BulkChangelogRequestBean {
    /// Request bean for bulk changelog retrieval
    pub fn new(issue_ids_or_keys: Vec<String>) -> BulkChangelogRequestBean {
        BulkChangelogRequestBean {
            field_ids: None,
            issue_ids_or_keys,
            max_results: None,
            next_page_token: None,
        }
    }
}

