/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-af24ef23962debd9cc35cf020799e57ab332dd33
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangedValueBean : Details of names changed in the record event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangedValueBean {
    /// The value of the field before the change.
    #[serde(rename = "changedFrom", skip_serializing_if = "Option::is_none")]
    pub changed_from: Option<String>,
    /// The value of the field after the change.
    #[serde(rename = "changedTo", skip_serializing_if = "Option::is_none")]
    pub changed_to: Option<String>,
    /// The name of the field changed.
    #[serde(rename = "fieldName", skip_serializing_if = "Option::is_none")]
    pub field_name: Option<String>,
}

impl ChangedValueBean {
    /// Details of names changed in the record event.
    pub fn new() -> ChangedValueBean {
        ChangedValueBean {
            changed_from: None,
            changed_to: None,
            field_name: None,
        }
    }
}

