/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1461af1efd5cc75bf21cb8256a8b42f9bd4278be
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerOfWorkflowSchemeAssociations : A container for a list of workflow schemes together with the projects they are associated with.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerOfWorkflowSchemeAssociations {
    /// A list of workflow schemes together with projects they are associated with.
    #[serde(rename = "values")]
    pub values: Vec<models::WorkflowSchemeAssociations>,
}

impl ContainerOfWorkflowSchemeAssociations {
    /// A container for a list of workflow schemes together with the projects they are associated with.
    pub fn new(values: Vec<models::WorkflowSchemeAssociations>) -> ContainerOfWorkflowSchemeAssociations {
        ContainerOfWorkflowSchemeAssociations {
            values,
        }
    }
}

