/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-37416ade0f89f7cb291510843b8a4bbd682b33a1
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerForWebhookIds : Container for a list of webhook IDs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerForWebhookIds {
    /// A list of webhook IDs.
    #[serde(rename = "webhookIds")]
    pub webhook_ids: Vec<i64>,
}

impl ContainerForWebhookIds {
    /// Container for a list of webhook IDs.
    pub fn new(webhook_ids: Vec<i64>) -> ContainerForWebhookIds {
        ContainerForWebhookIds {
            webhook_ids,
        }
    }
}

