/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-076cd4f44b0487c600c6a2c6fd87f6323c1ed5c5
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCrossProjectReleaseRequest {
    /// The cross-project release name.
    #[serde(rename = "name")]
    pub name: String,
    /// The IDs of the releases to include in the cross-project release.
    #[serde(rename = "releaseIds", skip_serializing_if = "Option::is_none")]
    pub release_ids: Option<Vec<i64>>,
}

impl CreateCrossProjectReleaseRequest {
    pub fn new(name: String) -> CreateCrossProjectReleaseRequest {
        CreateCrossProjectReleaseRequest {
            name,
            release_ids: None,
        }
    }
}

