/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-04504326a3bb85891591d523cc28ed61aefaa46b
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreatedIssue : Details about a created issue or subtask.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatedIssue {
    /// The ID of the created issue or subtask.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The key of the created issue or subtask.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The URL of the created issue or subtask.
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<String>,
    /// The response code and messages related to any requested transition.
    #[serde(rename = "transition", skip_serializing_if = "Option::is_none")]
    pub transition: Option<Box<models::NestedResponse>>,
    /// The response code and messages related to any requested watchers.
    #[serde(rename = "watchers", skip_serializing_if = "Option::is_none")]
    pub watchers: Option<Box<models::NestedResponse>>,
}

impl CreatedIssue {
    /// Details about a created issue or subtask.
    pub fn new() -> CreatedIssue {
        CreatedIssue {
            id: None,
            key: None,
            param_self: None,
            transition: None,
            watchers: None,
        }
    }
}

