/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-7dd452bf833f9d1d005d3d3d429c42e9aacb344e
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomFieldValueUpdateDetails : Details of updates for a custom field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldValueUpdateDetails {
    /// The list of custom field update details.
    #[serde(rename = "updates", skip_serializing_if = "Option::is_none")]
    pub updates: Option<Vec<models::CustomFieldValueUpdate>>,
}

impl CustomFieldValueUpdateDetails {
    /// Details of updates for a custom field.
    pub fn new() -> CustomFieldValueUpdateDetails {
        CustomFieldValueUpdateDetails {
            updates: None,
        }
    }
}

