/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-d0630ad8e2b33a2fc7347459a3397d94eb3a0393
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DashboardGadgetPosition : Details of a gadget position.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardGadgetPosition {
    #[serde(rename = "The column position of the gadget.")]
    pub the_column_position_of_the_gadget_period: i32,
    #[serde(rename = "The row position of the gadget.")]
    pub the_row_position_of_the_gadget_period: i32,
}

impl DashboardGadgetPosition {
    /// Details of a gadget position.
    pub fn new(the_column_position_of_the_gadget_period: i32, the_row_position_of_the_gadget_period: i32) -> DashboardGadgetPosition {
        DashboardGadgetPosition {
            the_column_position_of_the_gadget_period,
            the_row_position_of_the_gadget_period,
        }
    }
}

