/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1461af1efd5cc75bf21cb8256a8b42f9bd4278be
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FieldIdentifierObject : Identifier for a field for example FIELD\\_ID.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FieldIdentifierObject {
    #[serde(rename="FieldIdIdentifier")]
    FieldIdIdentifier {
        #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
        identifier: Option<serde_json::Value>,
    },
}

impl Default for FieldIdentifierObject {
    fn default() -> Self {
        Self::FieldIdIdentifier {
            identifier: Default::default(),
        }
        
    }
}


