/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-4f9780d932de14e7c3dec0c9382f8855050fda22
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FieldLayoutConfiguration : Defines the payload for the field layout configuration. See https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-field-configurations/\\#api-rest-api-3-fieldconfiguration-post
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldLayoutConfiguration {
    /// Whether to show the field
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<bool>,
    #[serde(rename = "pcri", skip_serializing_if = "Option::is_none")]
    pub pcri: Option<Box<models::ProjectCreateResourceIdentifier>>,
    /// Whether the field is required
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
}

impl FieldLayoutConfiguration {
    /// Defines the payload for the field layout configuration. See https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-field-configurations/\\#api-rest-api-3-fieldconfiguration-post
    pub fn new() -> FieldLayoutConfiguration {
        FieldLayoutConfiguration {
            field: None,
            pcri: None,
            required: None,
        }
    }
}

