/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-37416ade0f89f7cb291510843b8a4bbd682b33a1
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FromLayoutPayload : The payload for the layout details for the start end of a transition
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FromLayoutPayload {
    /// The port that the transition can be made from
    #[serde(rename = "fromPort", skip_serializing_if = "Option::is_none")]
    pub from_port: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<models::ProjectCreateResourceIdentifier>>,
    /// The port that the transition goes to
    #[serde(rename = "toPortOverride", skip_serializing_if = "Option::is_none")]
    pub to_port_override: Option<i32>,
}

impl FromLayoutPayload {
    /// The payload for the layout details for the start end of a transition
    pub fn new() -> FromLayoutPayload {
        FromLayoutPayload {
            from_port: None,
            status: None,
            to_port_override: None,
        }
    }
}

