/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-af42c50d50804c2f1b8ad4bb80d52c53890867e2
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetForgeAppPropertyKeys200ResponseKeysInner {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<String>,
}

impl GetForgeAppPropertyKeys200ResponseKeysInner {
    pub fn new() -> GetForgeAppPropertyKeys200ResponseKeysInner {
        GetForgeAppPropertyKeys200ResponseKeysInner {
            key: None,
            param_self: None,
        }
    }
}

