/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-04504326a3bb85891591d523cc28ed61aefaa46b
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCrossProjectReleaseResponse {
    /// The cross-project release name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The IDs of the releases included in the cross-project release.
    #[serde(rename = "releaseIds", skip_serializing_if = "Option::is_none")]
    pub release_ids: Option<Vec<i64>>,
}

impl GetCrossProjectReleaseResponse {
    pub fn new() -> GetCrossProjectReleaseResponse {
        GetCrossProjectReleaseResponse {
            name: None,
            release_ids: None,
        }
    }
}

