/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-37416ade0f89f7cb291510843b8a4bbd682b33a1
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPermissionHolderResponse {
    /// The permission holder type. This is \"Group\" or \"AccountId\".
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The permission holder value. This is a group name if the type is \"Group\" or an account ID if the type is \"AccountId\".
    #[serde(rename = "value")]
    pub value: String,
}

impl GetPermissionHolderResponse {
    pub fn new(r#type: Type, value: String) -> GetPermissionHolderResponse {
        GetPermissionHolderResponse {
            r#type,
            value,
        }
    }
}
/// The permission holder type. This is \"Group\" or \"AccountId\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Group")]
    Group,
    #[serde(rename = "AccountId")]
    AccountId,
}

impl Default for Type {
    fn default() -> Type {
        Self::Group
    }
}

