/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-37416ade0f89f7cb291510843b8a4bbd682b33a1
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueError : Describes the error that occurred when retrieving data for a particular issue.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueError {
    /// The error that occurred when fetching this issue.
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    /// The ID of the issue.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl IssueError {
    /// Describes the error that occurred when retrieving data for a particular issue.
    pub fn new() -> IssueError {
        IssueError {
            error_message: None,
            id: None,
        }
    }
}

