/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-2776b5c6be42695cc76ed18bb9006304d509a541
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JiraPriorityField {
    #[serde(rename = "priorityId")]
    pub priority_id: String,
}

impl JiraPriorityField {
    pub fn new(priority_id: String) -> JiraPriorityField {
        JiraPriorityField {
            priority_id,
        }
    }
}

