/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-4f9780d932de14e7c3dec0c9382f8855050fda22
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JiraDateField {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<Box<models::JiraDateInput>>,
    #[serde(rename = "fieldId")]
    pub field_id: String,
}

impl JiraDateField {
    pub fn new(field_id: String) -> JiraDateField {
        JiraDateField {
            date: None,
            field_id,
        }
    }
}

