/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-37416ade0f89f7cb291510843b8a4bbd682b33a1
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JiraRichTextField {
    #[serde(rename = "fieldId")]
    pub field_id: String,
    #[serde(rename = "richText")]
    pub rich_text: Box<models::JiraRichTextInput>,
}

impl JiraRichTextField {
    pub fn new(field_id: String, rich_text: models::JiraRichTextInput) -> JiraRichTextField {
        JiraRichTextField {
            field_id,
            rich_text: Box::new(rich_text),
        }
    }
}

