/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-4f9780d932de14e7c3dec0c9382f8855050fda22
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JqlQueryOrderByClause : Details of the order-by JQL clause.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JqlQueryOrderByClause {
    /// The list of order-by clause fields and their ordering directives.
    #[serde(rename = "fields")]
    pub fields: Vec<models::JqlQueryOrderByClauseElement>,
}

impl JqlQueryOrderByClause {
    /// Details of the order-by JQL clause.
    pub fn new(fields: Vec<models::JqlQueryOrderByClauseElement>) -> JqlQueryOrderByClause {
        JqlQueryOrderByClause {
            fields,
        }
    }
}

