/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-4168ca0e5efc137ea4ff4f0cf29358bf64e26f02
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LicenseMetric : A metric that provides insight into the active licence details
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseMetric {
    /// The key of a specific license metric.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The calculated value of a licence metric linked to the key. An example licence metric is the approximate number of user accounts.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl LicenseMetric {
    /// A metric that provides insight into the active licence details
    pub fn new() -> LicenseMetric {
        LicenseMetric {
            key: None,
            value: None,
        }
    }
}

