/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-076cd4f44b0487c600c6a2c6fd87f6323c1ed5c5
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// License : Details about a license for the Jira instance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct License {
    /// The applications under this license.
    #[serde(rename = "applications")]
    pub applications: Vec<models::LicensedApplication>,
}

impl License {
    /// Details about a license for the Jira instance.
    pub fn new(applications: Vec<models::LicensedApplication>) -> License {
        License {
            applications,
        }
    }
}

