/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-af42c50d50804c2f1b8ad4bb80d52c53890867e2
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MinimalFieldSchemeToFieldsPartialFailure : Minimal partial failure result when updating field scheme to fields associations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinimalFieldSchemeToFieldsPartialFailure {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "fieldId")]
    pub field_id: String,
    #[serde(rename = "schemeId")]
    pub scheme_id: i64,
    #[serde(rename = "success")]
    pub success: bool,
}

impl MinimalFieldSchemeToFieldsPartialFailure {
    /// Minimal partial failure result when updating field scheme to fields associations.
    pub fn new(field_id: String, scheme_id: i64, success: bool) -> MinimalFieldSchemeToFieldsPartialFailure {
        MinimalFieldSchemeToFieldsPartialFailure {
            error: None,
            field_id,
            scheme_id,
            success,
        }
    }
}

