/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-37416ade0f89f7cb291510843b8a4bbd682b33a1
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PreviewRuleConfiguration : Rule configuration for workflow transitions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreviewRuleConfiguration {
    /// A transient identifier for this element, unique within this response but not guaranteed to stable across requests.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The parameters of the rule.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<std::collections::HashMap<String, String>>,
    /// The rule key of the rule.
    #[serde(rename = "ruleKey", skip_serializing_if = "Option::is_none")]
    pub rule_key: Option<String>,
}

impl PreviewRuleConfiguration {
    /// Rule configuration for workflow transitions.
    pub fn new() -> PreviewRuleConfiguration {
        PreviewRuleConfiguration {
            id: None,
            parameters: None,
            rule_key: None,
        }
    }
}

