/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-d0630ad8e2b33a2fc7347459a3397d94eb3a0393
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectIssueTypeMapping : The project and issue type mapping.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectIssueTypeMapping {
    /// The ID of the issue type.
    #[serde(rename = "issueTypeId")]
    pub issue_type_id: String,
    /// The ID of the project.
    #[serde(rename = "projectId")]
    pub project_id: String,
}

impl ProjectIssueTypeMapping {
    /// The project and issue type mapping.
    pub fn new(issue_type_id: String, project_id: String) -> ProjectIssueTypeMapping {
        ProjectIssueTypeMapping {
            issue_type_id,
            project_id,
        }
    }
}

