/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-37416ade0f89f7cb291510843b8a4bbd682b33a1
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuickFilterPayload : The payload for defining quick filters
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuickFilterPayload {
    /// The description of the quick filter
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The jql query for the quick filter
    #[serde(rename = "jqlQuery", skip_serializing_if = "Option::is_none")]
    pub jql_query: Option<String>,
    /// The name of the quick filter
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl QuickFilterPayload {
    /// The payload for defining quick filters
    pub fn new() -> QuickFilterPayload {
        QuickFilterPayload {
            description: None,
            jql_query: None,
            name: None,
        }
    }
}

