/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-d0630ad8e2b33a2fc7347459a3397d94eb3a0393
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReorderIssuePriorities : Change the order of issue priorities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReorderIssuePriorities {
    /// The ID of the priority. Required if `position` isn't provided.
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
    /// The list of issue IDs to be reordered. Cannot contain duplicates nor after ID.
    #[serde(rename = "ids")]
    pub ids: Vec<String>,
    /// The position for issue priorities to be moved to. Required if `after` isn't provided.
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
}

impl ReorderIssuePriorities {
    /// Change the order of issue priorities.
    pub fn new(ids: Vec<String>) -> ReorderIssuePriorities {
        ReorderIssuePriorities {
            after: None,
            ids,
            position: None,
        }
    }
}

