/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-37416ade0f89f7cb291510843b8a4bbd682b33a1
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScreenableTab : A screen tab.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenableTab {
    /// The ID of the screen tab.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// The name of the screen tab. The maximum length is 255 characters.
    #[serde(rename = "name")]
    pub name: String,
}

impl ScreenableTab {
    /// A screen tab.
    pub fn new(name: String) -> ScreenableTab {
        ScreenableTab {
            id: None,
            name,
        }
    }
}

