/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-af42c50d50804c2f1b8ad4bb80d52c53890867e2
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

#![cfg(feature = "issues_api")]

use crate::models;
use serde::{Deserialize, Serialize};

/// Transitions : List of issue transitions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transitions {
    /// Expand options that include additional transitions details in the response.
    #[serde(rename = "expand", skip_serializing_if = "Option::is_none")]
    pub expand: Option<String>,
    /// List of issue transitions.
    #[serde(rename = "transitions", skip_serializing_if = "Option::is_none")]
    pub transitions: Option<Vec<models::IssueTransition>>,
}

impl Transitions {
    /// List of issue transitions.
    pub fn new() -> Transitions {
        Transitions {
            expand: None,
            transitions: None,
        }
    }
}
