/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-af42c50d50804c2f1b8ad4bb80d52c53890867e2
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateFieldAssociationSchemeResponse : Response object after successfully updating an existing field association scheme.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateFieldAssociationSchemeResponse {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<models::UpdateFieldAssociationSchemeLinksBean>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl UpdateFieldAssociationSchemeResponse {
    /// Response object after successfully updating an existing field association scheme.
    pub fn new() -> UpdateFieldAssociationSchemeResponse {
        UpdateFieldAssociationSchemeResponse {
            description: None,
            id: None,
            links: None,
            name: None,
        }
    }
}

