/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-076cd4f44b0487c600c6a2c6fd87f6323c1ed5c5
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateDefaultProjectClassificationBean : The request for updating the default project classification level.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDefaultProjectClassificationBean {
    /// The ID of the project classification.
    #[serde(rename = "id")]
    pub id: String,
}

impl UpdateDefaultProjectClassificationBean {
    /// The request for updating the default project classification level.
    pub fn new(id: String) -> UpdateDefaultProjectClassificationBean {
        UpdateDefaultProjectClassificationBean {
            id,
        }
    }
}

