/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-af42c50d50804c2f1b8ad4bb80d52c53890867e2
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateFieldSchemeParametersPartialFailure : Result of updating field scheme parameters for a specific field, scheme, and optional work type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateFieldSchemeParametersPartialFailure {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "fieldId")]
    pub field_id: String,
    #[serde(rename = "schemeId")]
    pub scheme_id: i64,
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "workTypeId", skip_serializing_if = "Option::is_none")]
    pub work_type_id: Option<i64>,
}

impl UpdateFieldSchemeParametersPartialFailure {
    /// Result of updating field scheme parameters for a specific field, scheme, and optional work type.
    pub fn new(field_id: String, scheme_id: i64, success: bool) -> UpdateFieldSchemeParametersPartialFailure {
        UpdateFieldSchemeParametersPartialFailure {
            error: None,
            field_id,
            scheme_id,
            success,
            work_type_id: None,
        }
    }
}

