/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-d0630ad8e2b33a2fc7347459a3397d94eb3a0393
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowUpdateRequest : The update workflows payload.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowUpdateRequest {
    /// The statuses to associate with the workflows.
    #[serde(rename = "statuses")]
    pub statuses: Vec<models::WorkflowStatusUpdate>,
    /// The details of the workflows to update.
    #[serde(rename = "workflows")]
    pub workflows: Vec<models::WorkflowUpdate>,
}

impl WorkflowUpdateRequest {
    /// The update workflows payload.
    pub fn new(statuses: Vec<models::WorkflowStatusUpdate>, workflows: Vec<models::WorkflowUpdate>) -> WorkflowUpdateRequest {
        WorkflowUpdateRequest {
            statuses,
            workflows,
        }
    }
}

