/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-6138e2cd7259ce8b18fff9d4a6cde29a4e1837b6
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowIds : The classic workflow identifiers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowIds {
    /// The entity ID of the workflow.
    #[serde(rename = "entityId", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<String>,
    /// The name of the workflow.
    #[serde(rename = "name")]
    pub name: String,
}

impl WorkflowIds {
    /// The classic workflow identifiers.
    pub fn new(name: String) -> WorkflowIds {
        WorkflowIds {
            entity_id: None,
            name,
        }
    }
}

