/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-076cd4f44b0487c600c6a2c6fd87f6323c1ed5c5
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowSchemeUsageDto : Workflow schemes using the workflow.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowSchemeUsageDto {
    /// The workflow ID.
    #[serde(rename = "workflowId", skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<String>,
    #[serde(rename = "workflowSchemes", skip_serializing_if = "Option::is_none")]
    pub workflow_schemes: Option<Box<models::WorkflowSchemeUsagePage>>,
}

impl WorkflowSchemeUsageDto {
    /// Workflow schemes using the workflow.
    pub fn new() -> WorkflowSchemeUsageDto {
        WorkflowSchemeUsageDto {
            workflow_id: None,
            workflow_schemes: None,
        }
    }
}

