/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-37416ade0f89f7cb291510843b8a4bbd682b33a1
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowMetadataRestModel : Workflow metadata and usage detail.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowMetadataRestModel {
    /// The description of the workflow.
    #[serde(rename = "description")]
    pub description: String,
    /// The ID of the workflow.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the workflow.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version")]
    pub version: Box<models::DocumentVersion>,
}

impl WorkflowMetadataRestModel {
    /// Workflow metadata and usage detail.
    pub fn new(description: String, id: String, name: String, version: models::DocumentVersion) -> WorkflowMetadataRestModel {
        WorkflowMetadataRestModel {
            description,
            id,
            name,
            version: Box::new(version),
        }
    }
}

