/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-4f9780d932de14e7c3dec0c9382f8855050fda22
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowMetadataRestModel : Workflow metadata and usage detail.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowMetadataRestModel {
    /// The description of the workflow.
    #[serde(rename = "description")]
    pub description: String,
    /// The ID of the workflow.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the workflow.
    #[serde(rename = "name")]
    pub name: String,
    /// Deprecated. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-2298) for details.  Use the optional `workflows.usages` expand to get additional information about the projects and issue types associated with the workflows in the workflow scheme.
    #[serde(rename = "usage", deserialize_with = "Option::deserialize")]
    pub usage: Option<Vec<models::SimpleUsage>>,
    #[serde(rename = "version")]
    pub version: Box<models::DocumentVersion>,
}

impl WorkflowMetadataRestModel {
    /// Workflow metadata and usage detail.
    pub fn new(description: String, id: String, name: String, usage: Option<Vec<models::SimpleUsage>>, version: models::DocumentVersion) -> WorkflowMetadataRestModel {
        WorkflowMetadataRestModel {
            description,
            id,
            name,
            usage,
            version: Box::new(version),
        }
    }
}

