/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-076cd4f44b0487c600c6a2c6fd87f6323c1ed5c5
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowSchemeIdName : The ID and the name of the workflow scheme.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowSchemeIdName {
    /// The ID of the workflow scheme.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the workflow scheme.
    #[serde(rename = "name")]
    pub name: String,
}

impl WorkflowSchemeIdName {
    /// The ID and the name of the workflow scheme.
    pub fn new(id: String, name: String) -> WorkflowSchemeIdName {
        WorkflowSchemeIdName {
            id,
            name,
        }
    }
}

