/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-076cd4f44b0487c600c6a2c6fd87f6323c1ed5c5
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowPreviewResponse : The preview workflow response containing workflows and statuses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowPreviewResponse {
    /// The list of statuses referenced by the workflows.
    #[serde(rename = "statuses", skip_serializing_if = "Option::is_none")]
    pub statuses: Option<Vec<models::JiraWorkflowPreviewStatus>>,
    /// The list of workflows. The workflows are returned in the same order as specified in the request.
    #[serde(rename = "workflows", skip_serializing_if = "Option::is_none")]
    pub workflows: Option<Vec<models::WorkflowPreview>>,
}

impl WorkflowPreviewResponse {
    /// The preview workflow response containing workflows and statuses.
    pub fn new() -> WorkflowPreviewResponse {
        WorkflowPreviewResponse {
            statuses: None,
            workflows: None,
        }
    }
}

